scrape_configs:
  - job_name: "transaction-service"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'transaction-service:8080' ]
        labels:
          alias: "transaction-service"